version: "3"

services:
  spark-master:
    image: docker.io/bitnami/spark:3.3.2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8080:8080
  spark-worker:
    image: docker.io/bitnami/spark:3.3.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  notebook:
    image: jupyter/all-spark-notebook:spark-3.3.2
    ports:
      - 8888:8888
      - 4040:4040
    environment:
       - PYSPARK_SUBMIT_ARGS=--packages com.amazonaws:aws-java-sdk-bundle:1.12.560,org.apache.hadoop:hadoop-aws:3.3.2 pyspark-shell
       - GRANT_SUDO=true
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - ./work:/home/jovyan/work
      - ./.jupyter:/home/jovyan/.jupyter
      #- ./jars:/home/jovyan/jars

  minio:
    image: "minio/minio:latest"
    volumes:
      - ./.storage/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: "root"
      MINIO_SECRET_KEY: "root12345"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3